[package]
name = "premonition-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "premonitiond"
path = "src/main.rs"

[dependencies]
clap.workspace = true
premonition-core = { path = "../premonition-core" }
premonition-executor = { path = "../premonition-executor" }
premonition-protocol = { path = "../premonition-protocol" }
sha2.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
